### ISSUE TITLE
Modal not working properly on Bootstrap 3.3.0

### ISSUE THREAD

**Issue by rafael-augusto** [myclabs/jquery.confirm#40]
After updating my Bootstrap.js to version 3.3.0, the jquery.confirm component is not working properly anymore. I can see the confirm dialog but the "modal-dialog" div is faded (as the background), plus the confirm button only closes the dialog and dont submit any action (like $.post(...))

**Comment by mnapoli** [comment]
Sorry but I'm gonna need a working example as I don't have a lot of time to try to reproduce myself.
