### ISSUE TITLE
jquery.confirm.js the css class is not in quotes

### ISSUE THREAD

**Issue by pablovidelayanez** [myclabs/jquery.confirm#45]
![modalheader](https://cloud.githubusercontent.com/assets/9121003/6733719/a65c1f24-ce32-11e4-88a7-784e4e934839.JPG)

**Comment by mnapoli** [comment]
Thank you I fixed it. I don't think it was breaking anything anyway.

**Comment by pablovidelayanez** [comment]
Maybe, but it's better be sure about that!,  great script :)

**Comment by mnapoli** [comment]
Yep definitely ;) Thanks I just released [a new version](https://github.com/myclabs/jquery.confirm/releases/tag/2.5.0) by the way
