### ISSUE TITLE
The dialog closes on overlay click

### ISSUE THREAD

**Issue by Kayparker** [myclabs/jquery.confirm#46]
I don't see any option to disable this. We do not want to close the modal on user action unless they click on buttons and/or close icon.

**Comment by mnapoli** [comment]
Hi, there is no option for that currently. If you need a custom behavior I encourage you to write the popup yourself, this library is just a small wrapper on top of Bootstrap's modals.

**Comment by Kayparker** [comment]
bootstrap do have options to configure this, this is required in many instances. If you can add this to your wrapper easily could help many.

**Comment by mnapoli** [comment]
@Kayparker OK I understand, then feel free to submit a pull request.
