### ISSUE TITLE
Suppress the cancel button? Add another button?

### ISSUE THREAD

**Issue by redskate** [myclabs/jquery.confirm#48]
Hi

very nice implementation :)

I was wandering whether it is possible to suppress the cancel button or to add further buttons... and call-backs

Thanks a lot
Cheers

**Comment by mnapoli** [comment]
Hi! Nope not possible. There is #33 for removing the cancel button, but customizing further is (I believe) out of scope: it is easy to create a custom popup from scratch.

**Comment by hidegh** [comment]
Simply add style (class) hidden, and cancel button won't be present.
