### ISSUE TITLE
Uncaught TypeError: h.modal is not a function

### ISSUE THREAD

**Issue by nrileykc** [myclabs/jquery.confirm#52]
Not sure what's up with it, but I keep getting the error: Uncaught TypeError: h.modal is not a function on one of my pages, but works on others.

```
Uncaught TypeError: h.modal is not a functiona.confirm @ jquery.confirm.min.js:14(anonymous function) @ jquery.confirm.min.js:14m.event.dispatch @ datatables.min.js:16r.handle @ datatables.min.js:16nrWrapper @ mixMatch?budget=50000&category=2&goal=1&startDate=&endDate=&rmDeliverable=509:6
```

**Comment by mnapoli** [comment]
Hi, do you have Bootstrap installed? It's a required dependency for this plugin.

**Comment by nrileykc** [comment]
Yes bootstrap is installed. Confirm works on other pages but not this one appears to possibly be a conflict of some kind. But I'm not fluent in jquery.

**Comment by mnapoli** [comment]
Mmhh to be honest it's quite hard for me to imagine what's going wrong on your page :/. I also unfortunately don't have much time to help out. I'll close the issue, if you identify a bug in this library please let me know we'll reopen.

**Comment by nrileykc** [comment]
This library and https://www.datatables.net/manual/styling/bootstrap bomb when on the page together was the issue.
