### ISSUE TITLE
Respect form submit name value

### ISSUE THREAD

**Issue by pawelad** [myclabs/jquery.confirm#65]
Its quite common to have a form with multiple buttons with `name` value set to know which button user pressed, like this:
```html
<button type="submit" name="delete_from_group">Delete from group</button>
<button type="submit" name="delete_forever">Delete forever</button>
```
Currently the plugin doesn't take this into consideration.

I managed to get this working basing the code on [this](https://github.com/Ifnot/PopConfirm/blob/v0.4.5/jquery.popconfirm.js) code from similar plugin:
```javascript
$(".confirm").confirm({
    confirm: function(button) {
        var form =  button.closest("form");
        if(typeof button.attr('name') !== "undefined") {
             $('<input type="hidden">').attr('name', button.attr('name')).attr('value', button.attr('value')).appendTo(form);
        }
        form.submit();
    }
});
```

I think that it would be nice to implement such behaviour by default.

I'm no JavaScript master, so I don't really know how 'hacky' is the code above - if it's good (or good *enough* ; ) I can submit a PR with the changes.

**Comment by entermix** [comment]
+1
Also faced with this problem.

**Comment by mnapoli** [comment]
Hi, I took some time to think about it and I don't think it should be included in this library. While I definitely understand your need and think it's valid, it's not a canonical usage of HTML forms. I don't think this library should support custom use case (or too many of them), it should focus on supporting classic HTML links, forms, etc. It's not shocking to me that what requires custom JS today (without this library) should still need custom JS with this lib.

Another reason is that this library is simple and should stay simple. It's fairly easy to add custom behavior (with the code example you showed) so it's a good balance between simple and extensible.

Hope it's fine with you!
