### ISSUE TITLE
Not able to attach the confirm event to un-rendered buttons in data table

### ISSUE THREAD

**Issue by mandarbt** [myclabs/jquery.confirm#66]
Hi,

I am using data table to show records and which can be deleted. I have used jquery.confirm for confirmation dialog. I am showing 10 rows in table for which confirmation works perfectly. But when pagination or sorting is done then for rest of the  records confirmation is not working. I tried '.on' but it didn't work. After using '.on' i need to click delete button twice, which i want to avoid.

Can somebody help me on this? Below is my code.

Html code:
  <table class="table table-responsive table-striped dataTable " id="tableD">
        <caption></caption>

        <thead>
            <tr>
                <th>Name</th>
                <th>FileType</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.FileTypeName</td>
                   <td>
                        <button type="button" title="Update" class="glyphicon glyphicon-pencil" onclick="EditClick(this)"></button>
                        <button type="button" value=@item.Id  title="Delete" class="confirm glyphicon glyphicon-trash" ></button>
                                            </td>
                    <td style="display:none">@item.DriverId</td>
                </tr>
            }
        </tbody>

    </table>

Javascript code:
$(document).ready(function () {
        
        $("#tableD").DataTable({
            ordering: false,
            sort: false,
            columnDefs: [{
                "defaultContent": "-",
                "targets": "_all"
            }]
        });

       
    })

   
    $('.confirm').confirm({
            title: "Delete Confirmation",
            text: "Do you want to delete row?",
            confirm: function (button) {
             
                 button.fadeOut(2000).fadeIn(2000);
                deleteItem(button.val(), "DeleteData") // Call delete method on confirmation
            },
            cancel: function (button) {
                button.fadeOut(2000).fadeIn(2000);

            },

            confirmButton: "Yes",
            cancelButton: "No",
            confirmButtonClass: "btn-default",
            cancelButtonClass: "btn-default"

        });

Thanks in advance.

**Comment by mnapoli** [comment]
Hi, I'm sorry but the issue tracker is not the place for user support. Try asking on stackoverflow or in the chatroom maybe.
