### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by antongorodezkiy** [myclabs/jquery.confirm#67]
Hello @myclabs people!

Thank you for the library. It's very useful.

For now it could be installed only via bower. Any plan to add NPM support?

**Comment by mnapoli** [comment]
Hi, no plan at this moment, if it's a matter of adding a JSON file feel free to send a pull request.

**Comment by antongorodezkiy** [comment]
No problem, for now ended up using https://www.npmjs.com/package/napa

**Comment by antongorodezkiy** [comment]
Sorry, my bad, really forgot about this issue item.

However currently I'm trying to use https://github.com/yarnpkg/yarn which is not working with https://github.com/shama/napa so that's why I asked this time.

**Comment by tristanbes** [comment]
Fixed in : https://github.com/myclabs/jquery.confirm/pull/84

**Comment by antongorodezkiy** [comment]
Thanks @tristanbes
