### ISSUE TITLE
I dont want to use bootstrap 

### ISSUE THREAD

**Issue by beshoo1** [myclabs/jquery.confirm#68]
Dear all , what if i dont like to use bootstrap ?
I am using semantic-ui.com. How can we implement semantic-ui.com insted of  bootstrap

Regards

**Comment by mnapoli** [comment]
Hi, this is not possible with this project, this library is a jquery + Bootstrap confirm.

**Comment by beshoo1** [comment]
No , it is , i just remove Bootstrap , and add a button classes red , green
, and blue ! , and modified how margen of confirmation made by add one
class to the script , you can even adjust it via the script. !

, do you like me so send you PL , to offer it as stand alone ?
