### ISSUE TITLE
Priority for the different sources of options

### ISSUE THREAD

**Issue by Deuteu** [myclabs/jquery.confirm#75]
About : https://github.com/myclabs/jquery.confirm/blob/master/jquery.confirm.js#L93
Shouldn't be dataOptions after options ?

Cause IMHO, dataOptions should be overriding options given that it's really related to only one element thus more specific.

**Comment by mnapoli** [comment]
Makes sense indeed, 👍

**Comment by mnapoli** [comment]
Fixed by #76
