### ISSUE TITLE
 Submit Form ( POST ) after Confirmation Yes / No

### ISSUE THREAD

**Issue by marcoczen** [myclabs/jquery.confirm#88]
Hi,

I have a bootstrap form with a submit button as below;
``
<button type="submit" class="btn btn-primary" name="button_deluser" > Delete Selected User </button>
``
When the button is clicked - the form is submitted. I would like a confirmation box (Yes - Delete, No ).
I dont understand how to incorporate jquery.confirm into the button above from the documentation provided. 

Any ideas ? Alert - Jquery newbie here.

**Comment by marcoczen** [comment]
IS this software broken completely with jquery 3.2.1 / bootstrap 3.3.7 ?

I tried adding class confirm to;

 <button type="submit"  name="button_edituser"    class="confirm btn btn-primary" > Edit Selected User </button>

And no confirmattion box popped up?
In the console ( F12) , i got SyntaxError: expected expression, got '<'  jquery.confirm.js:7

**Comment by mnapoli** [comment]
Hi, this library is not maintained anymore.

**Comment by marcoczen** [comment]
Noted.
Hope it gets revived.
